OWID_COVID = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv"
CFR_API = "https://microsites-live-backend.cfr.org/conflict/map/json"
GDACS = "https://www.gdacs.org/xml/rss_24h.xml"
CE_DF = "https://raw.githubusercontent.com/antonio-hickey/gDash/main/app/data/events/dataset.csv"
C19_DF = "https://raw.githubusercontent.com/antonio-hickey/gDash/main/app/data/covid/world_c19.csv"
GDP_DF = "https://raw.githubusercontent.com/antonio-hickey/gDash/main/app/data/economic/gdp.csv"
POP_DF = "https://raw.githubusercontent.com/antonio-hickey/gDash/main/app/data/demographics/population_by_country_2020.csv"
