name: Testing

on:
  pull_request:
  push:
    branches: [main]

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install python3.9
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
        python3 -m pip install --upgrade pip
        pip3 install -r test_requirements.txt
        pip3 install -r requirements.txt
    - name: Running Tests
      run: |
        python3 -m unittest
